### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by arash-ahmadi** [Sani-Abdullah/token-generator#1]
Hello Sani,

I am reaching out to you regarding the token generator , I have tested it with STS simulator and the generated tokens are giving Invalid CRC error. Appreciate if you can help me.
Regards

**Comment by Sani-Abdullah** [comment]
Dear Arash,

How urgently do you need my assistance? Can you give me 3 days. Thanks.
Regards

**Comment by arash-ahmadi** [comment]
Could you contact me at arash.ahmadi@live.com
I have a project which we can work with you. But the timing is very tight
